# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: book.proto
"""Generated protocol buffer code."""
from google.protobuf.internal import builder as _builder
from google.protobuf import descriptor as _descriptor
from google.protobuf import descriptor_pool as _descriptor_pool
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor_pool.Default().AddSerializedFile(b'\n\nbook.proto\x12\x04\x62ook\"$\n\x11\x43reate_book_reply\x12\x0f\n\x07success\x18\x01 \x01(\t\"\x86\x01\n\x04\x42ook\x12\x0c\n\x04ISBN\x18\x01 \x01(\t\x12\r\n\x05title\x18\x02 \x01(\t\x12\x0e\n\x06\x61uthor\x18\x03 \x01(\t\x12\x17\n\x0fpublishing_year\x18\x04 \x01(\x05\"8\n\x05Genre\x12\t\n\x05SCIFI\x10\x00\x12\n\n\x06HORROR\x10\x01\x12\x0b\n\x07ROMANCE\x10\x02\x12\x0b\n\x07\x46\x41NTASY\x10\x03\"\xa4\x01\n\x0eInventory_Item\x12\x18\n\x10inventory_number\x18\x05 \x01(\x05\x12\x0e\n\x04ISBN\x18\x01 \x01(\tH\x00\x12\x0f\n\x05title\x18\x02 \x01(\tH\x00\x12\x10\n\x06\x61uthor\x18\x03 \x01(\tH\x00\x12\x19\n\x0fpublishing_year\x18\x04 \x01(\x05H\x00\"\"\n\x06STATUS\x12\r\n\tAVAILABLE\x10\x00\x12\t\n\x05TAKEN\x10\x01\x42\x06\n\x04\x42ook2n\n\x10InventoryService\x12\x34\n\x0b\x43reate_Book\x12\n.book.Book\x1a\x17.book.Create_book_reply\"\x00\x12$\n\x08Get_Book\x12\n.book.Book\x1a\n.book.Book\"\x00\x62\x06proto3')

_builder.BuildMessageAndEnumDescriptors(DESCRIPTOR, globals())
_builder.BuildTopDescriptorsAndMessages(DESCRIPTOR, 'book_pb2', globals())
if _descriptor._USE_C_DESCRIPTORS == False:

  DESCRIPTOR._options = None
  _CREATE_BOOK_REPLY._serialized_start=20
  _CREATE_BOOK_REPLY._serialized_end=56
  _BOOK._serialized_start=59
  _BOOK._serialized_end=193
  _BOOK_GENRE._serialized_start=137
  _BOOK_GENRE._serialized_end=193
  _INVENTORY_ITEM._serialized_start=196
  _INVENTORY_ITEM._serialized_end=360
  _INVENTORY_ITEM_STATUS._serialized_start=318
  _INVENTORY_ITEM_STATUS._serialized_end=352
  _INVENTORYSERVICE._serialized_start=362
  _INVENTORYSERVICE._serialized_end=472
# @@protoc_insertion_point(module_scope)
